name: Deploy to VPS

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/frontend-estudamais
            git pull origin main
            npm install
            npm run build
            docker build -t frontend-estudamais .
            docker rm -f frontend-estudamais || true
            docker run -d --name frontend-estudamais -p 8503:80 frontend-estudamais
